### ISSUE TITLE
UnrecognizedPropertyException when findGoodById throw error

### ISSUE THREAD

**Issue by dimaloop** [deniskristov/checkbox-api-client#4]
Hi!

Got a com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException when call findGoodById() method (for example, passed not uuid):

`com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "detail" (class ua.in.checkbox.api.client.dto.ErrorDetails), not marked as ignorable (one known property: "message"])
 at [Source: (String)"{"detail":[{"loc":["path","good_id"],"msg":"value is not a valid uuid","type":"type_error.uuid"}],"message":"Validation error"}"; line: 1, column: 12] (through reference chain: ua.in.checkbox.api.client.dto.ErrorDetails["detail"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:987)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1701)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1679)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:330)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
	at ua.in.checkbox.api.client.CheckboxApiClient.getForObjectImpl(CheckboxApiClient.java:282)
	at ua.in.checkbox.api.client.CheckboxApiClient.getForObject(CheckboxApiClient.java:235)
	at ua.in.checkbox.api.client.CheckboxApiClient.findGoodById(CheckboxApiClient.java:129)`

Not urgent, just noticed to be known issue

**Comment by deniskristov** [comment]
ErrorDetails wasn't mapped properly.
Fixed.

P.S. pay attention to the underlying API error response, you provided an incorrect product UUID.
